export const styles = {
  root: {
    fontFamily: "'IBM Plex Sans', 'Segoe UI', sans-serif",
    minHeight: "100vh",
    background: "#0d1520",
    color: "#eaf0fb",
    position: "relative",
  },
  confluenceBox: {
    marginTop: "1.5rem",
    padding: "1.25rem",
    background: "#0f1923",
    border: "1px solid #1a2a3a",
    borderRadius: 12,
  },
  confluenceHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "1rem",
    flexWrap: "wrap",
    marginBottom: "1rem",
    paddingBottom: "0.75rem",
    borderBottom: "1px solid #1a2a3a",
  },
  confluenceEyebrow: {
    fontSize: "0.7rem",
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "#4fa3ff",
    marginBottom: 4,
  },
  confluenceTitle: {
    fontSize: "1.05rem",
    fontWeight: 700,
    color: "#eaf0fb",
  },
  confluenceOpenLink: {
    color: "#4fa3ff",
    fontSize: "0.85rem",
    fontWeight: 600,
    textDecoration: "none",
  },
  confluenceBody: {
    color: "#eaf0fb",
    lineHeight: 1.6,
    fontSize: "0.95rem",
    wordBreak: "break-word",
  },
  confluenceStatus: {
    color: "#8899aa",
    fontSize: "0.9rem",
    padding: "1rem 0",
  },
  confluenceStatusBox: {
    marginTop: "1rem",
    marginBottom: "1rem",
    padding: "0.85rem 1rem",
    background: "#0d1520",
    border: "1px solid #1a2a3a",
    borderRadius: 10,
  },
  confluencePicked: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "1rem",
    padding: "0.75rem 1rem",
    background: "#0d1520",
    border: "1px solid #1a2a3a",
    borderRadius: 10,
  },
  confluenceResults: {
    marginTop: "0.5rem",
    maxHeight: 260,
    overflow: "auto",
    border: "1px solid #1a2a3a",
    borderRadius: 8,
    background: "#0d1520",
  },
  confluenceResult: {
    width: "100%",
    textAlign: "left",
    display: "block",
    padding: "0.6rem 0.85rem",
    background: "transparent",
    border: "none",
    borderBottom: "1px solid #1a2a3a",
    color: "#eaf0fb",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: "0.9rem",
  },
  tabRow: {
    display: "flex",
    gap: 4,
    marginBottom: "1rem",
    borderBottom: "1px solid #1a2a3a",
  },
  tabBtn: {
    border: "none",
    background: "transparent",
    color: "#8899aa",
    fontFamily: "inherit",
    fontWeight: 700,
    fontSize: "0.85rem",
    padding: "0.5rem 1rem",
    cursor: "pointer",
    borderBottom: "2px solid transparent",
  },
  tabBtnActive: {
    color: "#4fa3ff",
    borderBottom: "2px solid #4fa3ff",
  },
  notification: {
    position: "fixed",
    top: "1rem",
    right: "1rem",
    padding: "0.75rem 1.25rem",
    borderRadius: 8,
    color: "#fff",
    fontWeight: 600,
    fontSize: "0.9rem",
    zIndex: 9999,
    boxShadow: "0 8px 24px rgba(0, 0, 0, 0.45), 0 0 0 1px rgba(79, 163, 255, 0.25)",
  },

  homeWrap: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background:
      "linear-gradient(160deg, #0a1220 0%, #0d1520 40%, #12243a 100%)",
    position: "relative",
    overflow: "hidden",
  },
  homeDeco: {
    position: "absolute",
    width: 520,
    height: 520,
    borderRadius: "50%",
    right: "-120px",
    top: "-80px",
    background:
      "radial-gradient(circle, rgba(79, 163, 255, 0.28) 0%, rgba(26, 107, 210, 0.12) 40%, transparent 70%)",
    pointerEvents: "none",
    filter: "blur(2px)",
  },
  homeInner: {
    textAlign: "center",
    zIndex: 1,
    padding: "2rem",
    maxWidth: 640,
    width: "100%",
  },
  homeBadge: {
    display: "inline-block",
    background: "rgba(79, 163, 255, 0.12)",
    color: "#4fa3ff",
    border: "1px solid rgba(79, 163, 255, 0.35)",
    borderRadius: 999,
    padding: "0.35rem 0.9rem",
    fontSize: "0.72rem",
    fontWeight: 700,
    letterSpacing: "0.14em",
    marginBottom: "1.25rem",
  },
  homeTitle: {
    fontSize: "clamp(2.2rem, 5vw, 3.4rem)",
    fontWeight: 800,
    lineHeight: 1.15,
    margin: "0 0 1rem",
    color: "#eaf0fb",
    letterSpacing: "-0.02em",
  },
  homeSubtitle: {
    color: "#8899aa",
    fontSize: "1.1rem",
    margin: "0 0 2.25rem",
    lineHeight: 1.5,
  },
  homeBtns: {
    display: "flex",
    gap: "0.75rem",
    flexWrap: "wrap",
    justifyContent: "center",
  },

  primaryBtn: {
    background: "linear-gradient(135deg, #4fa3ff 0%, #1a6bd2 100%)",
    color: "#fff",
    border: "none",
    padding: "0.8rem 1.5rem",
    borderRadius: 8,
    fontWeight: 600,
    fontSize: "0.95rem",
    cursor: "pointer",
    fontFamily: "inherit",
    display: "inline-flex",
    alignItems: "center",
    gap: "0.5rem",
    boxShadow: "0 8px 20px rgba(26, 107, 210, 0.35), 0 0 0 1px rgba(79, 163, 255, 0.2)",
  },
  ghostBtn: {
    background: "transparent",
    color: "#eaf0fb",
    border: "1px solid #1a2a3a",
    padding: "0.8rem 1.5rem",
    borderRadius: 8,
    fontWeight: 600,
    fontSize: "0.95rem",
    cursor: "pointer",
    fontFamily: "inherit",
    display: "inline-flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  btnIcon: {
    fontSize: "0.85rem",
    lineHeight: 1,
  },
  editBtn: {
    background: "transparent",
    color: "#4fa3ff",
    border: "1px solid #1a2a3a",
    padding: "0.35rem 0.85rem",
    borderRadius: 6,
    cursor: "pointer",
    fontSize: "0.85rem",
    fontWeight: 600,
    fontFamily: "inherit",
  },
  dangerBtn: {
    background: "transparent",
    color: "#ff6b6b",
    border: "1px solid rgba(192, 57, 43, 0.45)",
    padding: "0.35rem 0.85rem",
    borderRadius: 6,
    cursor: "pointer",
    fontSize: "0.85rem",
    fontWeight: 600,
    fontFamily: "inherit",
  },
  cancelBtn: {
    background: "transparent",
    color: "#8899aa",
    border: "1px solid #1a2a3a",
    padding: "0.35rem 0.85rem",
    borderRadius: 6,
    cursor: "pointer",
    fontSize: "0.85rem",
    fontFamily: "inherit",
  },
  backBtn: {
    background: "transparent",
    color: "#4fa3ff",
    border: "none",
    cursor: "pointer",
    fontSize: "0.9rem",
    padding: "0.75rem 1rem",
    textAlign: "left",
    marginTop: "1rem",
    fontFamily: "inherit",
    fontWeight: 600,
  },

  appWrap: {
    display: "flex",
    minHeight: "100vh",
  },
  navScrim: {
    position: "fixed",
    inset: 0,
    border: "none",
    padding: 0,
    margin: 0,
    background: "rgba(0,0,0,0.45)",
    zIndex: 30,
    cursor: "pointer",
  },
  mobileBar: {
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
    marginBottom: "1rem",
  },
  menuBtn: {
    background: "#111e2c",
    color: "#eaf0fb",
    border: "1px solid #1a2a3a",
    borderRadius: 8,
    padding: "0.45rem 0.85rem",
    fontWeight: 700,
    fontSize: "0.85rem",
    cursor: "pointer",
    fontFamily: "inherit",
  },
  mobileBarTitle: {
    color: "#8899aa",
    fontSize: "0.9rem",
    fontWeight: 600,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  sidebar: {
    width: 260,
    background: "#0b1622",
    borderRight: "1px solid #1a2a3a",
    display: "flex",
    flexDirection: "column",
    padding: "1.5rem 0",
    flexShrink: 0,
  },
  sidebarHeader: {
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
    padding: "0 1rem 1.5rem",
    borderBottom: "1px solid #1a2a3a",
    marginBottom: "1rem",
  },
  sidebarLogo: {
    width: 38,
    height: 38,
    borderRadius: 10,
    background: "linear-gradient(135deg, #4fa3ff 0%, #1a6bd2 100%)",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
    fontSize: "0.95rem",
    flexShrink: 0,
    boxShadow: "0 4px 12px rgba(26, 107, 210, 0.4)",
  },
  sidebarTitle: { fontWeight: 700, fontSize: "1rem", lineHeight: 1.2, color: "#eaf0fb" },
  sidebarSub: { fontSize: "0.75rem", color: "#4fa3ff" },
  searchInput: {
    margin: "0 1rem 1rem",
    background: "#111e2c",
    border: "1px solid #1a2a3a",
    borderRadius: 8,
    padding: "0.6rem 0.8rem",
    color: "#eaf0fb",
    fontSize: "0.9rem",
    outline: "none",
    fontFamily: "inherit",
  },
  catList: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    padding: "0 0.5rem",
    overflowY: "auto",
    flex: 1,
  },
  catBtn: {
    background: "transparent",
    border: "none",
    color: "#8899aa",
    padding: "0.55rem 0.75rem",
    borderRadius: 8,
    cursor: "pointer",
    fontSize: "0.87rem",
    textAlign: "left",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontFamily: "inherit",
  },
  catBtnActive: {
    background: "rgba(79, 163, 255, 0.12)",
    color: "#eaf0fb",
    fontWeight: 600,
  },
  catCount: {
    color: "#8899aa",
    fontSize: "0.75rem",
  },
  main: {
    flex: 1,
    padding: "2rem",
    overflowY: "auto",
    maxHeight: "100vh",
    background: "#0d1520",
  },
  mainHeader: {
    display: "flex",
    alignItems: "baseline",
    gap: "1rem",
    marginBottom: "1.5rem",
    borderBottom: "1px solid #1a2a3a",
    paddingBottom: "1rem",
  },
  mainTitle: {
    fontSize: "1.6rem",
    fontWeight: 700,
    margin: 0,
    color: "#eaf0fb",
  },
  mainCount: {
    color: "#8899aa",
    fontSize: "0.9rem",
  },
  empty: {
    color: "#8899aa",
    textAlign: "center",
    marginTop: "4rem",
    fontSize: "1.05rem",
  },
  loadErrorBox: {
    marginTop: "3rem",
    textAlign: "center",
    maxWidth: 420,
    marginLeft: "auto",
    marginRight: "auto",
  },
  loadErrorText: {
    color: "#8899aa",
    fontSize: "1rem",
    lineHeight: 1.6,
    marginBottom: "1.25rem",
  },

  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))",
    gap: "1rem",
  },
  card: {
    background: "#111e2c",
    border: "1px solid #1a2a3a",
    borderRadius: 12,
    padding: "1.25rem",
    cursor: "pointer",
    position: "relative",
    overflow: "hidden",
    boxShadow: "0 4px 16px rgba(0, 0, 0, 0.25)",
  },
  cardAccent: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 3,
  },
  cardCat: {
    fontSize: "0.72rem",
    fontWeight: 700,
    color: "#4fa3ff",
    marginBottom: "0.5rem",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  cardTitle: {
    fontSize: "1.05rem",
    fontWeight: 600,
    marginBottom: "0.5rem",
    lineHeight: 1.3,
    color: "#eaf0fb",
  },
  cardSnippet: {
    color: "#8899aa",
    fontSize: "0.85rem",
    lineHeight: 1.5,
    marginBottom: "0.75rem",
  },
  cardTags: { display: "flex", gap: "0.4rem", flexWrap: "wrap", marginBottom: "0.75rem" },
  tag: {
    background: "rgba(79, 163, 255, 0.12)",
    color: "#4fa3ff",
    padding: "0.15rem 0.5rem",
    borderRadius: 999,
    fontSize: "0.72rem",
    fontWeight: 600,
  },
  cardArrow: {
    color: "#4fa3ff",
    fontSize: "0.82rem",
    fontWeight: 600,
  },

  detail: {
    maxWidth: 760,
  },
  detailBack: {
    background: "transparent",
    border: "none",
    color: "#4fa3ff",
    cursor: "pointer",
    fontSize: "0.9rem",
    padding: "0 0 1.5rem",
    display: "block",
    fontFamily: "inherit",
    fontWeight: 600,
  },
  detailCat: {
    fontSize: "0.72rem",
    fontWeight: 700,
    color: "#4fa3ff",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    marginBottom: "0.5rem",
  },
  detailTitle: {
    fontSize: "2rem",
    fontWeight: 700,
    marginBottom: "2rem",
    lineHeight: 1.2,
    color: "#eaf0fb",
  },
  detailSection: {
    background: "#111e2c",
    border: "1px solid #1a2a3a",
    borderRadius: 12,
    padding: "1.5rem",
    marginBottom: "1.5rem",
  },
  detailSectionLabel: {
    fontSize: "0.75rem",
    fontWeight: 700,
    color: "#4fa3ff",
    marginBottom: "0.75rem",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  detailBody: {
    color: "#eaf0fb",
    lineHeight: 1.7,
    margin: 0,
  },
  stepList: {
    margin: 0,
    padding: 0,
    listStyle: "none",
    display: "flex",
    flexDirection: "column",
    gap: "0.65rem",
  },
  stepItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: "1rem",
    background: "#0d1520",
    border: "1px solid #1a2a3a",
    borderRadius: 10,
    padding: "0.85rem 1rem",
  },
  stepNum: {
    background: "#1a6bd2",
    color: "#fff",
    borderRadius: "50%",
    width: 26,
    height: 26,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "0.8rem",
    fontWeight: 700,
    flexShrink: 0,
  },
  stepText: { flex: 1, color: "#eaf0fb", fontSize: "0.95rem", lineHeight: 1.5 },
  detailTags: { display: "flex", gap: "0.5rem", flexWrap: "wrap" },
  tagLarge: {
    background: "rgba(79, 163, 255, 0.12)",
    color: "#4fa3ff",
    padding: "0.3rem 0.7rem",
    borderRadius: 999,
    fontSize: "0.82rem",
    fontWeight: 600,
  },

  loginWrap: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background:
      "linear-gradient(160deg, #0a1220 0%, #0d1520 40%, #12243a 100%)",
  },
  loginBox: {
    background: "#111e2c",
    border: "1px solid #1a2a3a",
    borderRadius: 16,
    padding: "2.5rem",
    width: "100%",
    maxWidth: 400,
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
    alignItems: "stretch",
    boxShadow: "0 16px 40px rgba(0, 0, 0, 0.4)",
  },
  loginIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    background: "linear-gradient(135deg, #4fa3ff 0%, #1a6bd2 100%)",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1.25rem",
    marginBottom: "0.25rem",
    boxShadow: "0 6px 16px rgba(26, 107, 210, 0.4)",
  },
  loginTitle: {
    textAlign: "left",
    margin: 0,
    fontSize: "1.75rem",
    fontWeight: 700,
    color: "#eaf0fb",
  },
  loginSub: {
    textAlign: "left",
    color: "#8899aa",
    fontSize: "0.9rem",
    margin: "0 0 0.5rem",
  },
  loginInput: {
    background: "#0d1520",
    border: "1px solid #1a2a3a",
    borderRadius: 8,
    padding: "0.75rem 1rem",
    color: "#eaf0fb",
    fontSize: "1rem",
    outline: "none",
    fontFamily: "inherit",
  },
  loginError: {
    color: "#ff6b6b",
    fontSize: "0.85rem",
  },

  adminStats: {
    display: "flex",
    gap: "0.5rem",
    padding: "0 1rem 1.5rem",
  },
  statBox: {
    flex: 1,
    background: "#111e2c",
    borderRadius: 10,
    padding: "0.75rem",
    textAlign: "center",
    border: "1px solid #1a2a3a",
  },
  statNum: { fontSize: "1.5rem", fontWeight: 700, color: "#4fa3ff" },
  statLabel: { fontSize: "0.7rem", color: "#8899aa", marginTop: 2 },
  adminTable: {
    background: "#111e2c",
    border: "1px solid #1a2a3a",
    borderRadius: 12,
    overflow: "hidden",
  },
  tableHead: {
    display: "flex",
    padding: "0.75rem 1.25rem",
    background: "#0b1622",
    borderBottom: "1px solid #1a2a3a",
    fontSize: "0.75rem",
    fontWeight: 700,
    color: "#8899aa",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  },
  tableRow: {
    display: "flex",
    padding: "1rem 1.25rem",
    borderBottom: "1px solid #1a2a3a",
    alignItems: "center",
    gap: "0.5rem",
  },
  deleteConfirm: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
    flex: 1,
    color: "#ff6b6b",
    fontSize: "0.9rem",
    flexWrap: "wrap",
  },

  formWrap: {
    maxWidth: 680,
  },
  formTitle: {
    fontSize: "1.6rem",
    fontWeight: 700,
    marginBottom: "1.5rem",
    color: "#eaf0fb",
  },
  label: {
    display: "block",
    fontSize: "0.78rem",
    fontWeight: 700,
    letterSpacing: "0.08em",
    color: "#4fa3ff",
    textTransform: "uppercase",
    marginBottom: "0.4rem",
    marginTop: "1rem",
  },
  checkLabel: {
    display: "flex",
    alignItems: "center",
    gap: "0.6rem",
    marginTop: "1.25rem",
    color: "#eaf0fb",
    fontSize: "0.95rem",
    fontWeight: 600,
    cursor: "pointer",
  },
  input: {
    width: "100%",
    background: "#111e2c",
    border: "1px solid #1a2a3a",
    borderRadius: 8,
    padding: "0.75rem 1rem",
    color: "#eaf0fb",
    fontSize: "0.95rem",
    outline: "none",
    resize: "vertical",
    fontFamily: "inherit",
    boxSizing: "border-box",
  },
  select: {
    width: "100%",
    background: "#111e2c",
    border: "1px solid #1a2a3a",
    borderRadius: 8,
    padding: "0.75rem 1rem",
    color: "#eaf0fb",
    fontSize: "0.95rem",
    outline: "none",
    boxSizing: "border-box",
    fontFamily: "inherit",
  },
  formActions: {
    display: "flex",
    gap: "1rem",
    marginTop: "2rem",
    flexWrap: "wrap",
  },
  formInlineError: {
    background: "rgba(192, 57, 43, 0.15)",
    border: "1px solid rgba(192, 57, 43, 0.45)",
    color: "#ff6b6b",
    padding: "0.65rem 1rem",
    borderRadius: 8,
    fontSize: "0.9rem",
    marginBottom: "0.5rem",
  },
};

